name: Build "Lightink"

on:
  workflow_dispatch:

jobs:
  start_building_turnip:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3

    - name: Prepare environment
      run: |
        sudo sed -i 's/^Types: deb$/Types: deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt update
        sudo apt install openjdk-11-jdk wget unzip git -y

    - name: Execute build script
      run: bash ./build.sh

    - name: Release "Lightink"
      uses: softprops/action-gh-release@v1
      with:
        body: Turnip build for android
        tag_name: Turnip
        name: Release
        files: |
           lightink/app/build/outputs/apk/debug/app-debug.apk
